version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Laravel
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1